name: finance_tracker
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  provider: ^6.0.0
  intl: ^0.19.0
  fl_chart: ^0.68.0
  flutter_svg: ^2.0.10+1
  csv: ^6.0.0
  open_file: ^3.2.1
  workmanager: ^0.5.2
  flutter_local_notifications: ^17.2.2
  shared_preferences: ^2.0.15
  http: ^1.2.2
  connectivity_plus: ^6.0.5
  qr_code_scanner: ^1.0.0
  file_picker: ^5.2.7
  permission_handler: ^11.1.0
  google_mobile_ads: ^5.1.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:

  uses-material-design: true
  assets:
    - assets/images/savings_light.svg
    - assets/images/savings_dark.svg
    - assets/images/no_data_light.svg
    - assets/images/no_data_dark.svg
    - assets/languages/en.json
    - assets/languages/es.json
    - assets/languages/pt.json
    - assets/languages/fr.json
    - .env